'use strict';

require('./CreateTables.js');
require('./InsertProductBottomJeans.js');
require('./InsertProductBottomShortJeans.js');
require('./InsertProductBottomWorkingTrousers.js');
require('./InsertProductBottomWorkingShorts.js');
require('./InsertProductBottomCottonTrousers.js');
require('./InsertProductBottomCottonShorts.js');
require('./InsertProductBasicPlainTee.js');
require('./InsertProductBasicPlainRoundNeckTee.js');
require('./InsertProductBasicPlainHatLongTee.js');
require('./InsertProductCoatBaseBallCoat.js');
require('./InsertProductCoatFlightCoat.js');
require('./InsertProductCoatCowboyCoat.js');
require('./InsertProductCoatHoodedCoat.js');
require('./InsertProductCoatWindCoat.js');
require('./InsertProductTopKid.js');
require('./InsertProductTopLongSleeveTop.js');
require('./InsertProductAccessoriesHat.js');
require('./InsertProductAccessoriesScoks.js');
require('./InsertProductAccessoriesAccessories.js');
require('./InsertProductAccessoriesPhoneCase.js');
require('./InsertProductAccessoriesBag.js');
require('./InsertProductTopHoodedTee.js');
require('./InsertProductTopShirt.js');
require('./InsertProductTopVest.js');
